package jADVJ2EE;

public class ExceptionHandling {

	public static void main(String[] args) {   //JVM in main handle by using throws and Exception name 
		// TODO Auto-generated method stub
        
		System.out.println("Main method started here");
		
		int a = 10, b = 0, c;
		try
		{
		c = a / b;
		
		System.out.println(c);
		}
		catch(Exception e)  //Exception e is supur class in java.  (ArithmeticException e)
		{
			System.out.println(e); //can't devided by zero .
		}
		System.out.println("main method Ended");
	}

}

/*
   output screen :- exception handling 

Main method started here
Exception in thread "main" java.lang.ArithmeticException: / by zero
	at jADVJ2EE.ExceptionHandling.main(ExceptionHandling.java:12)


try catch using exception handling output:-


Main method started here
java.lang.ArithmeticException: / by zero
main method Ended

*/